name: Deploy BlazorGravatarDemo to GitHub Pages

on:
  push:
    branches:
      - github-pages  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' 

    # Step 3: Build the BlazorGravatarDemo project
    - name: Build the BlazorGravatarDemo project
      run: |
        dotnet publish BlazorGravatarDemo/BlazorGravatarDemo.csproj -c Release -o output

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output/wwwroot
